version: '3.8'
services:
  app:
    container_name: ollama-frontend
    build:
      context: .
      target: development
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
